#+title:      My Gratitude Journal
#+date:       [2024-04-19 Fri 16:32]
#+filetags:   :priv:
#+identifier: 20240419T163220

* Begin my gratitude journal in this nuc machine.

* 2024-04-24

** Thank you God for ending my day safely. I ask for your guidance as I sleep and be ready for the next day. Thank you for guiding us from harm, me, my family and sibs back home. I ask for your daily guidance as we travel in the journey of life.

* 2024-04-21
** Last night i sleep better so thank you dear God for giving me another day to wake up to. I pray for your guidance and blessings for completing this day as well as those of my family. Thank you always.
** I also ask for your blessing to give me the knowledge and understand to learn programming especially this Common Lisp that interest me this time of the year.

* 2024-04-20
** Thank you God for giving me another day of my life. I'm feeling much better today than last night and i thank you for it.
** Today I ask you to guide me in my daily tasks especially in my medical blood chem checkup later today in Hofuf hospital.
** Please guide and make safe my family back home especially today they are out for a field trip in Guimaras. Keep them from harm as they travel from Iloilo to Guimaras and back.

* 2024-04-19
** Thank you Lord for another day of existence. Thanks for the reminder that health is very important for us to maintain as we continue in this journey of life.
** Yesterday even though its late already to go to the hospital and get myself checked its OK since this is all for myself. It is all a learning experience.
** Today i begin resuming my healthy ways. Its hard but its the only way.
